# Generated by Django 5.2.6 on 2025-09-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('ball', 'Ball'), ('jersey', 'Jersey'), ('shorts', 'Shorts'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('training gear', 'Training Gear')], max_length=50),
        ),
    ]
